---
title: "About"
---

## Background

I have a bachelor's degree in Computer Science and Engineeringfrom Mekelle Institute of Technology, Ethiopia. Through my studies and previous experiences, I developed a strong foundation in data analytics, AI/ML model development, and programming using Python, R, and SQL.

I am deeply passionate about transforming complex data into actionable insights and developing data-driven solutions that support better decision-making and build stronger communities.

Beyond my technical work, I have volunteer experience in national and international community development. I am also passionate about sustainability, women’s empowerment, and creating opportunities for underserved communities.

As the Founder of the Data for Change initiative and a Sustainability Ambassador at the University of British Columbia, I am committed to connecting data-driven innovation with social and environmental impact.

I strongly believe that data and AI are most powerful when they are used to empower people and create positive change.

My goal is to continue bridging data insights and social impact by modeling data-driven solutions that contribute to a more inclusive, sustainable, and equitable future.

## Why Data Science

I am interested in using data science to understand real-world problems and support better decision-making. I joined the MDS program to strengthen my skills in data analysis, machine learning, and data-driven problem solving.

## Outside of Data Science

Outside of my studies, I enjoy exploring new places, spending time with friends, and learning about different communities and cultures. Since arriving in Vancouver, I have also enjoyed discovering the city and balancing graduate school with life outside the classroom.